config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :employers, path: 'employers', controllers: {sessions: 'employers/sessions', registrations: 'employers/registrations', confirmations: 'employers/confirmations'}
  # eg. http://localhost:3000/employers/sign_in
  devise_for :employees, path: 'employees', controllers: {sessions: 'employees/sessions', registrations: 'employees/registrations', confirmations: 'employees/confirmations'}
  # eg. http://localhost:3000/employees/sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.or/routing.html
  resources :job_postings do
    scope module: :job_postings do
      resources :job_applications
    end
  end

  resources :job_applications do
  patch '/accept', to: 'job_applications#accept'
  patch '/reject', to: 'job_applications#reject'
  end

  resources :employee_profiles
  resources :employer_profiles
  
  authenticated :employee do
    root 'job_postings#index', as: :employees
  end

  authenticated :employer do
    root 'job_postings#index', as: :employers
  end
  
  root 'landing_pages#index'

end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :profession
  belongs_to :employer
  has_many :employees, through: :job_applications
  has_many :feedbacks
  has_many :job_applications

  include Discard::Model
  default_scope -> { kept }

  validates(:content, presence: true)
end

app/controllers/job_postings/job_applications_controller.rb
module JobPostings
  class JobApplicationsController < ApplicationController
    before_action :set_job_posting
    before_action :set_job_application, except: [:create]
    before_action :check_user

    def create
      @job_application = @job_posting.job_applications.new(employee: current_employee, status: 2)
      if already_applied?
        redirect_to root_path, alert: "You can't apply more than once"
      else 
        @job_application.save
        redirect_to root_path, notice: 'Job Application was successful.'
      end
    end

    def show
      @job_posting = JobPosting.find(params[:job_posting_id])
      @job_application = JobApplication.find(params[:id])
    end

    def index
      @job_application.order
    end

    private

    def job_applications_params
      params.permit(:status, :id, :job_posting_id, :employee_id, :employer_id)
    end  

    def set_job_posting
      @job_posting = JobPosting.find(params[:job_posting_id])
    end

    def set_job_application
      @job_application = JobApplication.find(params[:id])
    end

    def already_applied?
      JobApplication.where(employee_id: current_employee.id, job_posting_id:
      params[:job_posting_id]).exists?
    end

    def order
      JobApplication.where(created_at: 1.month.ago.to_date..Date.current)
    end

  end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :find_job_posting, only: [:show, :edit, :update, :destroy]
  
  def index
    # @job_postings = @job_postings.order('created_at DESC')
    @job_postings = if current_employer
                      current_employer.job_postings.order("created_at desc")
                    elsif current_employee
                      JobPosting.all.order("created_at desc")
                    end
  end

  def new
    @job_posting = JobPosting.new
  end

  def create
    @job_posting = JobPosting.new(job_postings_params)
    
    if @job_posting.save
      redirect_to @job_posting
    else
      render :new
    end
  end

  def show
  end

  def update
    if @job_posting.update(job_postings_params)
      redirect_to @job_posting
    else
      render :edit
    end
  end

  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.discard
    redirect_to root_path, notice: 'Job Posting Discarded'
  end

  def undiscard
    @job_posting = JobPosting.find(params[:id])
    @job_posting.undiscard
    redirect_to root_path, notice: 'Job Application Undiscarded'
  end

  private
  
  def job_postings_params
    params.require(:job_posting).permit(
      :title, :content, :start_time, :end_time, :hourly_rate, :profession_id
    ).merge(employer_id: current_employer.id)
  end

  def find_job_posting
    @job_posting = JobPosting.find(params[:id])
  end

  def order
    JobPosting.where(created_at: 1.month.ago.to_date..Date.current)
  end

  # def status
  #   @status = JobApplication.all(read_attribute(:status))
  # end

end

app/views/job_postings/_applicant.html.erb
<%= link_to job_posting_job_application_path(@job_posting, application), class: "col-mc-1-1 col-md-1-3" do %>
  <div class="section-panel">
    <div class="flex flex--nowrap">
      <div>
        <% if application.employee.employee_profile.avatar.attached? %>
          <%= image_tag application.employee.employee_profile.avatar, style: 'height: 120px' %>
        <% else %>
          <%= image_tag 'default.jpg', style: 'height: 120px' %>
        <% end %>
      </div>
      <div>
        <div class="section-panel__inner">
          <span class="card__content_dark_text" style="margin-bottom: 0.6rem">
              <%= application.employee.employee_profile.full_name %>
          </span>
          <p class="body-text" style="margin-bottom: 0">
            <%= truncate(application.employee.employee_profile.bio, length: 35) %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/job_postings/_form.html.erb
<section>
  <article class="card">
    <div>
      <%= form_with(model: @job_posting, local: true) do |form| %>
        <% if @job_posting.errors.present? %>
          <% @job_posting.errors.full_messages.each do |error| %>
            <p><%= error %></p> 
          <% end %>
        <% end %>
          </ul>
        </div>
        
      <div class="card__body">
      <h3 class= 'form-row justify-content-center text-center'>New Job Posting</h3>
      </div>

      <div class="card__body">
      <h5 class="card__title">Title:</h5>
        <%= form.text_field :title, class: 'form-control' %>
    </div>


      <div class="card__body">
      <h5 class="card__title">Hourly Rate:</h5>
          <%= form.number_field :hourly_rate, step: :any, class: 'form-control', placeholder: '£ 0.00' %>
      </div>

      <div class="card__body">
        <h5 class="card__title">Content:</h5>
        <p class="card__content">
            <%= form.text_area :content, class: 'form-control' %>
        </p>
      </div>

        <div class="card__body">
          <div class="form in-line mx-auto">
            <h5 class="card__title__job_post">Start Time:</h5>
            <h5 class="card__title__job_post">End Time:</h5>
          </div>
        </div>

      <div class="card__body__job_post">
        <div class="row">
          <div class="col-md-4">
            <p class="card__content">
                <%= form.text_field :start_time, class: 'form-control datepicker' %>
            </p>
          </div>
   
          <div class="col-md-4">
              <p class="card__content">
                <%= form.text_field :end_time, class: 'form-control datepicker' %>
              </p>
          </div>
      </div>
      </div>
      <%# </div> %>

      <%# <div class= 'form-row justify-content-center text-center'>
      
      </div> %>

      <div class="card__body">
        <h5 class="card__title">Profession:</h5>
        <p class="card__content">
          <%= form.collection_select :profession_id, Profession.all, :id, :name, {prompt: "Choose a profession" }, class: 'form-control' %>
        </p>
      </div>


  <footer class="card__footer">
  <%= form.submit "Submit", class: 'btn btn-primary' %>
      <span class="vertical-divider"></span>
  <%= link_to 'Back', @employee_profile, class: 'btn btn-primary' %>
  </footer>


      <% end %>

app/views/job_postings/_posting.html.erb
<div class="section-panel section-panel--theme">
  <div class="section-panel__inner">
    <div class="flex flex--align-items flex--justify-between">
      <h3 style="font-size: 2.75rem"><%= link_to "#{job.title} @ #{job.employer.employer_profile.business_name}", job, class: 'text-white' %></h3>
      <div style="background: white; padding: 5px 15px 5px 30px;border-radius: 30px;">
        <% if job.profession.name == 'Chef' %>
          <%= link_to image_tag('kitchen_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% elsif job.profession.name == 'Catering Manager' %>
          <%= link_to image_tag('catering_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% elsif job.profession.name == 'Bar Tender' %>
          <%= link_to image_tag('bar_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% end %>
      </div>
    </div>
    <hr class="horizontal-divider">
    <div class="text-white"><%= simple_format(job.content) %></div>
    <hr class="horizontal-divider">
    <div class="flex flex--gutters">
      <div class="text-white"><strong>Start: </strong><%= job.start_time.strftime("%d %b %Y at %H:%m") %></div>
      <div><span class="vertical-divider"></span></div>
      <div class="text-white"><strong>End: </strong><%= job.end_time.strftime("%d %b %Y at %H:%m")%></div>
      <div><span class="vertical-divider"></span></div>
      <div class="text-white"><strong>Hourly Rate: </strong><%= job.hourly_rate %></div>
    </div>  
  </div>
</div>
<br>
<br>

app/views/job_postings/index.html.erb
<% if current_employee %>
  <% current_employee.employee_profile.profession.job_postings.order("created_at DESC").each do |job| %>
    <%= render 'job_postings/posting', job: job %>
  <% end %>
<% else %>
  <% if current_employer && @job_postings.blank? %>
    <div class="section-panel section-panel--theme">
      <div class="section-panel">
        <div class="section-panel__inner">
          <h4 class="text-white">You do not have any job postings yet.</h4>
          <div style="margin-top: 40px">
            <%= link_to 'New Posting', new_job_posting_path, class: 'button button--secondary' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @job_postings.each do |job| %>
    <%# if job.start_time > Time.current %> 
      <%= render 'job_postings/posting', job: job %>
    <%# end %>
  <% end %>
<% end %>

app/views/job_postings/new.html.erb
<%= render 'form' %>

app/views/job_postings/show.html.erb
<div class="section-panel section-panel--theme">
  <div class="section-panel__inner">
    <div class="flex flex--align-items flex--justify-between">
      <h3 class="text-white" style="font-size: 2.75rem"><%= @job_posting.title %> @ <%= @job_posting.employer.employer_profile.business_name %></h3>
      <div style="background: white; padding: 5px 15px 5px 30px;border-radius: 30px;">
        <% if @job_posting.profession.name == 'Chef' %>
          <%= link_to image_tag('kitchen_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% elsif @job_posting.profession.name == 'Catering Manager' %>
          <%= link_to image_tag('catering_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% elsif @job_posting.profession.name == 'Bar Tender' %>
          <%= link_to image_tag('bar_rgb.svg', height: 40, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <% end %>
      </div>
    </div>
    <hr class="horizontal-divider">
    <div class="text-white"><%= simple_format(@job_posting.content) %></div>
    <hr class="horizontal-divider">
    <div class="flex flex--gutters">
      <div class="text-white"><strong>Start: </strong><%= @job_posting.start_time.strftime("%d %b %Y at %H:%m") %></div>
      <div><span class="vertical-divider"></span></div>
      <div class="text-white"><strong>End: </strong><%= @job_posting.end_time.strftime("%d %b %Y at %H:%m")%></div>
      <div><span class="vertical-divider"></span></div>
      <div class="text-white"><strong>Hourly Rate: </strong><%= @job_posting.hourly_rate %></div>
    </div>  
    <hr class="horizontal-divider">
    <div class="flex">
      <% if current_employee %>
        <%= form_with(model: JobApplication.new, url: job_posting_job_applications_path(@job_posting), local: true) do |form| %>
          <%= form.submit 'Apply', data: { confirm: 'Please confirm your application by clicking OK:' }, class: 'button button--secondary' %>
        <% end %> 
      <% end %>
      <% if current_employer %>
        <%= link_to 'Delete', [@job_posting], method: :delete, data: { confirm: 'Are you sure you want to delete this job posting?' }, class: 'button button--danger' %>
      <% end %>
    </div>
  </div>
</div>

<% if current_employer %>
  <br>
  <h1 class="subheading text-white" style="margin-bottom: 20px">Applicants</h1>

  <% if current_employer && @job_posting.job_applications.applied.blank? %>
    <div class="section-panel section-panel--theme">
      <div class="section-panel__inner">
        <h4 class="text-white">You do not have any applications yet.</h4>      
      </div>
    </div>
  <% end %>

  <div class="flex flex--gutters-2x">
    <% @job_posting.job_applications.applied.each do |job_application| %>
      <%= render 'applicant', application: job_application %>
    <% end %>
  </div>
  
<% end %>