config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :employers, path: 'employers', controllers: {sessions: 'employers/sessions', registrations: 'employers/registrations', confirmations: 'employers/confirmations'}
  # eg. http://localhost:3000/employers/sign_in
  devise_for :employees, path: 'employees', controllers: {sessions: 'employees/sessions', registrations: 'employees/registrations', confirmations: 'employees/confirmations'}
  # eg. http://localhost:3000/employees/sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.or/routing.html
  resources :job_postings do
    scope module: :job_postings do
      resources :job_applications
    end
  end

  resources :job_applications do
  patch '/accept', to: 'job_applications#accept'
  patch '/reject', to: 'job_applications#reject'
  end

  resources :employee_profiles
  resources :employer_profiles
  
  authenticated :employee do
    root 'job_postings#index', as: :employees
  end

  authenticated :employer do
    root 'job_postings#index', as: :employers
  end
  
  root 'landing_pages#index'

end

app/models/employer_profile.rb
class EmployerProfile < ApplicationRecord
  belongs_to :employer

  validates :first_name, :last_name, :business_name, presence: true

  has_one_attached :avatar

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/employer_profiles_controller.rb
class EmployerProfilesController < ApplicationController
  before_action :set_employer_profile, only: [:show, :edit, :update, :destroy]

  def index
  end

  # GET /employer_profiles/1
  # GET /employer_profiles/1.json
  def show
  end

  # GET /employer_profiles/new
  def new
    @employer_profile = current_employer.build_employer_profile
  end

  # GET /employer_profiles/1/edit
  def edit
  end

  # POST /employer_profiles
  # POST /employer_profiles.json
  def create
    @employer_profile = current_employer.build_employer_profile(employer_profile_params)

    respond_to do |format|
      if @employer_profile.save
        format.html { redirect_to @employer_profile, notice: 'Employer profile was successfully created.' }
        format.json { render :show, status: :created, location: @employer_profile }
      else
        format.html { render :new }
        format.json { render json: @employer_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employer_profiles/1
  # PATCH/PUT /employer_profiles/1.json
  def update
    respond_to do |format|
      if @employer_profile.update(employer_profile_params)
        format.html { redirect_to @employer_profile, notice: 'Employer profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer_profile }
      else
        format.html { render :edit }
        format.json { render json: @employer_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employer_profiles/1
  # DELETE /employer_profiles/1.json
  def destroy
    @employer_profile.destroy
    respond_to do |format|
      format.html { redirect_to employer_profiles_url, notice: 'Employer profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer_profile
      @employer_profile = EmployerProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_profile_params
      params.require(:employer_profile).permit(:first_name, :last_name, :business_name, :avatar)
    end
end

app/helpers/employer_profiles_helper.rb
module EmployerProfilesHelper
end

app/views/employer_profiles/_form.html.erb
<section class="card-container__profile">
    <article>
      
      <%= form_with(model: employer_profile, local: true) do |form| %>
        <% if employer_profile.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(employer_profile.errors.count, "error") %> prohibited this employer_profile from being saved:</h2>
            <ul>
              <% employer_profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

          <div class="card__header">
            <div class="card__body__profile">
            <br>
              <% if @employer_profile.avatar.attached? %>
                <%= image_tag(@employer_profile.avatar, :class => "card__image__profile") %>
              <% else %>
                <%= image_tag('default.jpg', :class => "card__image__profile") %>
              <% end %>
            <br>
              <div class="card__body__profile">
                <h5 class="card__title">Business Picture:</h5>
                <p class="card__content">
                  <%= form.file_field :avatar, class: "filestyle", "data-input" => false %>
                </p>
              </div>
            </div>
            <span>
              <div class="card__body"></div>
            </span>
            <div class="card__body__profile">
            <br>
              <h5 class="card__title">First Name:</h5>
              <p class="card__content">
                <%= form.text_field :first_name, class: 'form-control' %>
              </p>
    
              <h5 class="card__title">Last Name:</h5>
              <p class="card__content">
                <%= form.text_field :last_name, class: 'form-control' %>
              </p>
    
              <h5 class="card__title">Business Name:</h5>
              <p class="card__content">
                <%= form.text_field :business_name, class: 'form-control' %>
              </p>
            </div>
          </div>
          <div class="col-xs-1 center-block" style="text-align:center">
            <%= form.submit :Submit, class: 'button button--primary' %>
          </div>
          <br>
          <div class="col-xs-1 center-block" style="text-align:center">
            <%= link_to 'Back', @employer_profile, class: 'button button--tertiary'%>
          </div>
        </div>
      <% end %>
    </article>
  </section>

app/views/employer_profiles/edit.html.erb
<div class= 'form-row justify-content-center text-center'>
  <h1>Editing Employer Profile</h1>
</div>

<%= render 'form', employer_profile: @employer_profile %>

app/views/employer_profiles/index.html.erb
<%= link_to root_path %>

app/views/employer_profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', employer_profile: @employer_profile %>

app/views/employer_profiles/show.html.erb
<h2>Profile</h2>
<section class="card-container__profile">
  <article>
    <div class="card__header">
      <div class="card__body">
        <% if @employer_profile.avatar.attached? %>
          <%= image_tag(@employer_profile.avatar, :class => "card__image__profile") %>
        <% else %>
          <%= image_tag('default.jpg', :class => "card__image__profile") %>
        <% end %>
        </div>
      <br>
      <div class="card__body">
        <h5 class="card__title">Name:</h5>
        <p class="card__content">
          <%= @employer_profile.full_name %>
        </p>
        <h5 class="card__title">Business Name:</h5>
        <p class="card__content">
          <%= @employer_profile.business_name %>
        </p>
        <h5 class="card__title">Job Postings Count:</h5>
        <p class="card__content">
          <%= link_to @employer_profile.employer.job_postings.count, job_postings_path %>
        </p>
      </div>
    </div>
        <div class="col-xs-1 center-block" style="text-align:center;">
        <%= link_to 'Edit', edit_employer_profile_path(@employer_profile), class: 'button button--primary' %>
        </div>
        <br>
        <div class="col-xs-1 center-block" style="text-align:center;">
        <%= link_to 'Back', root_path, class: 'button button--tertiary' %>
      </div>
  </article>
</section>
<br>
<h2>Past Applications</h2>
<br>
<section>
  <% if current_employer %>
    <% @current_employer.job_postings.order("created_at DESC").each do |post|%>
      <%= render 'job_postings/posting', job: post %>
    <% end %>
  <% end %>
</section>