config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :employers, path: 'employers', controllers: {sessions: 'employers/sessions', registrations: 'employers/registrations', confirmations: 'employers/confirmations'}
  # eg. http://localhost:3000/employers/sign_in
  devise_for :employees, path: 'employees', controllers: {sessions: 'employees/sessions', registrations: 'employees/registrations', confirmations: 'employees/confirmations'}
  # eg. http://localhost:3000/employees/sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.or/routing.html
  resources :job_postings do
    scope module: :job_postings do
      resources :job_applications
    end
  end

  resources :job_applications do
  patch '/accept', to: 'job_applications#accept'
  patch '/reject', to: 'job_applications#reject'
  end

  resources :employee_profiles
  resources :employer_profiles
  
  authenticated :employee do
    root 'job_postings#index', as: :employees
  end

  authenticated :employer do
    root 'job_postings#index', as: :employers
  end
  
  root 'landing_pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :employer
  belongs_to :employee_Profile
  validates :employer_id, presence: true
  validates :employee_profile_id, presence: true
  validates :content, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one :employee_profile, dependent: :destroy
  accepts_nested_attributes_for :employee_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  has_many :job_applications
  has_many :job_postings, through: :job_applications
  has_many :feedbacks

  
end

app/models/employee_profile.rb
class EmployeeProfile < ApplicationRecord
  belongs_to :employee
  belongs_to :profession
  validates :profession_id, presence: true

  has_one_attached :avatar

  def full_name
    first_name + ' ' + last_name
  end

end

app/models/employer.rb
class Employer < ApplicationRecord
  has_one :employer_profile, dependent: :destroy
  accepts_nested_attributes_for :employer_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :job_postings
end

app/models/employer_profile.rb
class EmployerProfile < ApplicationRecord
  belongs_to :employer

  validates :first_name, :last_name, :business_name, presence: true

  has_one_attached :avatar

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :job_posting
    belongs_to :employee
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
    belongs_to :job_posting
    belongs_to :employee

    include Discard::Model
    default_scope -> { kept }
    scope :kept, -> { undiscarded.joins(:job_posting).merge(JobPosting.kept) }


    enum status: { accepted: 0, rejected: 1, applied: 2, not_applied: 3 }

    
    # accepts_nested_attributes_for :employer, allow_destroy: true

    # validates(:content, presence: true)
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :profession
  belongs_to :employer
  has_many :employees, through: :job_applications
  has_many :feedbacks
  has_many :job_applications

  include Discard::Model
  default_scope -> { kept }

  validates(:content, presence: true)
end

app/models/job_posting_skill.rb
class JobPostingSkill < ApplicationRecord
  belongs_to :job_posting
  belongs_to :skill
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :job_postings
  has_many :employee_profiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Accessible
    
  #Passing parameters for submitting the form 
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u|
        u.permit(:email, :password, :password_confirmation, 
        :employee_profile_attributes => [:first_name, :last_name, :profession_id], 
        :employer_profile_attributes => [:business_name, :first_name, :last_name])
      }
    columns = %i[email password password_confirmation]
    devise_parameter_sanitizer.permit(:account_update, keys: columns)   
  end

  before_action :check_user


  def check_user
      if current_employer
        # flash.clear
        # if you have rails_admin. You can redirect anywhere really
        #redirect_to(rails_employer.dashboard_path) && return
      elsif current_employee
        # flash.clear
        # The authenticated root path can be defined in your routes.rb in: devise_scope :user do...
        # redirect_to(authenticated_employee_root_path) && return
      else
        authenticate_employee!
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
  end

  def destroy
  end
  
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :find_job_posting, only: [:show, :edit, :update, :destroy]
  
  def index
    # @job_postings = @job_postings.order('created_at DESC')
    @job_postings = if current_employer
                      current_employer.job_postings.order("created_at desc")
                    elsif current_employee
                      JobPosting.all.order("created_at desc")
                    end
  end

  def new
    @job_posting = JobPosting.new
  end

  def create
    @job_posting = JobPosting.new(job_postings_params)
    
    if @job_posting.save
      redirect_to @job_posting
    else
      render :new
    end
  end

  def show
  end

  def update
    if @job_posting.update(job_postings_params)
      redirect_to @job_posting
    else
      render :edit
    end
  end

  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.discard
    redirect_to root_path, notice: 'Job Posting Discarded'
  end

  def undiscard
    @job_posting = JobPosting.find(params[:id])
    @job_posting.undiscard
    redirect_to root_path, notice: 'Job Application Undiscarded'
  end

  private
  
  def job_postings_params
    params.require(:job_posting).permit(
      :title, :content, :start_time, :end_time, :hourly_rate, :profession_id
    ).merge(employer_id: current_employer.id)
  end

  def find_job_posting
    @job_posting = JobPosting.find(params[:id])
  end

  def order
    JobPosting.where(created_at: 1.month.ago.to_date..Date.current)
  end

  # def status
  #   @status = JobApplication.all(read_attribute(:status))
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_profiles_helper.rb
module EmployeeProfilesHelper
end

app/helpers/employer_profiles_helper.rb
module EmployerProfilesHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer", class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">© 2019 Copyright: SlackingAround Team
    <a href= '#'></a>
    <a href= '#'></a>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<% if employer_signed_in? %>
    <%= render 'layouts/navbar/employer'%>
<% elsif employee_signed_in? %>
    <%= render 'layouts/navbar/employee'%>
<% else %>
    <%= render 'layouts/navbar/main_nav'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shiift</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.filestyle/1.1.0/js/bootstrap-filestyle.min.js"> </script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <%= stylesheet_link_tag 'main/navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div class="content-wrap" id="page-content">
      <% if flash.alert %>
        <div class="alert alert-danger" role="alert">
          <%= flash.alert %>
        </div>
      <% end %>
      <% if flash.notice %>
        <div class="alert alert-success" role="alert">
          <%= flash.notice %>
        </div>
      <% end %>
        <div class="content-main">
          <%= yield %>
        </div>
    </div>
    
  </body>
  
  <%= render "layouts/footer" %>

</html>

app/views/layouts/navbar/_employee.html.erb
<div style="margin-top: 30px">
  <div class="content-wrap">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to image_tag('logo_rgb_reverse.svg', height: 50, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <button class="custom-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Applications', job_applications_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class='navbar-nav ml-auto'>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= current_employee.email %></a>
                  <div class="dropdown-divider"></div>
                  <% if current_employee.employee_profile == nil %>
                    <%= link_to 'Create Profile', new_employee_profile_path, class: "dropdown-item" %>
                  <% else %>
                    <%= link_to 'Profile', current_employee.employee_profile, class: "dropdown-item" %>
                  <% end %>  
                <div class="dropdown-divider"></div>
                  <%= link_to 'Log Out', destroy_employee_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
      </div>
      </nav>
  </div>
</div>

app/views/layouts/navbar/_employer.html.erb
<div style="margin-top: 30px">
    <div class="content-wrap">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to image_tag('logo_rgb_reverse.svg', height: 50, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <button class="custom-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Applications', job_applications_path, class: "nav-link" %>
            </li>
      
            <li class="nav-item active">
              <%= link_to 'New Job Post', new_job_posting_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class='navbar-nav ml-auto'>  
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <p class="dropdown-item"><%= current_employer.email %></p>
                <div class="dropdown-divider"></div>
                  <% if current_employer.employer_profile == nil %>
                    <%= link_to 'Create Profile', new_employer_profile_path, class: "dropdown-item" %>
                  <% else %>
                    <%= link_to 'Profile', current_employer.employer_profile, class: "dropdown-item" %>
                  <% end %>
                <div class="dropdown-divider"></div>
                  <%= link_to 'Log Out', destroy_employer_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
  </div>
</div>
  

app/views/layouts/navbar/_main_nav.html.erb
<div style="margin-top: 30px">
  <div class="content-wrap">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to image_tag('logo_rgb_reverse.svg', height: 50, alt: "Brand"), root_path, class: 'navbar-brand' %>
        <button class="custom-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav navbar-nav ml-auto">
            <li>
              <a><%= link_to 'Employee', employee_session_path, class: "nav-link" %></a>
            </li>
            <li>
              <a><%= link_to 'Employer', employer_session_path, class: "nav-link" %></a>
            </li>
          </ul>
        </div>
      </nav>      
  </div>
</div>